---
title: "Author Contributions Checklist Form"
date: "Revision: 11/5/2019"
output:
  html_document: default
  pdf_document: default
  word_document: default
---
<!--HOW TO COMPLETE THIS FORM:-->

<!-- 
1. This is a Markdown document, which requires an interpreter to compile into its final version form. RStudio can compile Markdown documents, as can other open-source tools [provide more detail here].  -->
<!-- 
In your submission, please include: -->
<!-- 
a) This file (with extension .Rmd or .md)  -->
<!-- 
b) A compiled version of this form in PDF or .docx format 
-->

<!-- 
2. Checkboxes in this document appear as follows: -->
<!-- 
- [ ] This is a checkbox -->
<!-- 
To check a checkbox, replace [ ] by [x], as follows: -->
<!-- 
- [x] This is a checked checkbox -->

<!-- 
3. For text answers, simply type the relevant text in the areas indicated. A blank line starts a new paragraph. -->

<!-- 
4. Comments (like these instructions) provide additional instructions throughout the form. There is no need to remove them; they will not appear in the compiled document. -->

<!-- 
5. If you are comfortable with Markdown syntax, you may choose to include any Markdown-compliant formatting in the form. For example, you may wish to include R code chunks and compile this document in R Markdown.  -->

<!-- 
6. If you have any problems completing this form, please contact jasa.app.cs.aer@gmail.com  -->

The purpose of the Author Contributions Checklist (ACC) Form is to document the artifacts associated with a manuscript (i.e., the data and code supporting the computational findings) and describe how to reproduce the findings. The final version of this document is included as online supplemental material with the published paper and on the JASA Github site (http://github.com/JASA-ACS/) and is referenced in the abstract.


ACC forms for published papers can be seen in the Supplementary Materials section of each paper on the JASA website, as well as within the README file of each paper's JASA GitHub repository (http://github.com/JASA-ACS/). Examples of high-quality reproducibility materials are provided at YYYYYYYYYYYYYY.

# Data

- [ ] This paper does not involve analysis of external data (i.e., no data are used or the only data are generated by the authors via simulation in their code).

<!--
If box above is checked, please skip directly to the Code section. Otherwise, continue.
-->

- [ ] I certify that the author(s) of the manuscript have legitimate access to and permission to use the data used in this manuscript.

## Abstract

<!--
Provide a short (< 10 words), high-level description of the data
-->

## Availability

- [ ] Data **are** publicly available
- [ ] Data **cannot be made** publicly available

If the data are publicly available, see the *Publicly available data* section. Otherwise, see the *Non-publicly available data* section, below.

### Publicly available data

<!--
If the data for this manuscript are not publicly available, skip to the Non-publicly available section below. Otherwise, continue.
-->

- [ ] Data are available online at:

- [ ] Data are available as part of the paper’s supplementary material.

- [ ] Data are publicly available by request, following the process described here:

- [ ] Data are or will be made available through some other mechanism, described below:

### Non-publicly available data

<!--
If the data for this manuscript are publicly available, skip to the Description section below. Otherwise, complete this section
-->

The Journal of the American Statistical Association requires authors to make data accompanying their papers available to the scientific community except in cases where: 1) public sharing of data would be impossible, 2) suitable synthetic data are provided which allow the main analyses to be replicated (recognizing that results may differ from the "real" data analyses), and 3) the scientific value of the results and methods outweigh the lack of reproducibility.

Discussion of lack of publicly available data:
-	why data sharing is not possible,
-	what synthetic data are provided, and 
-	why the value of the paper's scientific contribution outweighs the lack of reproducibility.

## Description

### File format(s)

<!--
Check all that apply
-->
- [ ] CSV or other plain text
- [ ] Software-specific binary format (.Rda, Python pickle, etc.):
- [ ] Standardized binary format (e.g., netCDF, HDF5, etc.): 
- [ ] Other (please specify):

### Data dictionary

- [ ] Provided by authors in the following file(s):
- [ ] Data file(s) is(are) self-descripting (e.g., netCDF files)
- [ ] Available at the following URL: 

## Additional Information (optional)

### Additional details

<!-- 
OPTIONAL: Provide any additional details that would be helpful in understanding the data
-->

### Unique identifier/DOI/version information

<!--
OPTIONAL: Provide identifier information
-->

### License or terms of use

<!--
OPTIONAL: Provide licensing information
-->

# Code

## Abstract

<!--
Provide a short (< 10 words), high-level description of the code
-->

## Description

### Code format(s)

<!--
Check all that apply
-->

- [ ] Script files
    - [ ] R
    - [ ] Python
    - [ ] Matlab
    - [ ] Other: 
- [ ] Package
    - [ ] R
    - [ ] Python
    - [ ] MATLAB toolbox
    - [ ] Other: 
- [ ] Reproducible report 
    - [ ] R Markdown
    - [ ] Jupyter notebook
    - [ ] Other:
- [ ] Shell script
- [ ] Other (please specify): 

### Supporting software requirements

#### Version of primary software used

<!--
(e.g., R version 3.6.0)
-->

#### Libraries and dependencies used by the code

<!--
Include version numbers (e.g., version numbers for any R or Python packages used)
-->

### Supporting hardware requirements (optional)

<!--
Hardware requirements including operating system with version number, access to cluster, GPUs, etc.
-->

### Parallelization used

- [ ] No parallel code used
- [ ] Multi-core parallelization on a single machine/node
    - Number of cores used: 
- [ ] Multi-machine/multi-node parallelization 
    - Number of nodes and cores used: 

### License

- [ ] MIT License (default)
- [ ] BSD 
- [ ] GPL v3.0
- [ ] Creative Commons
- [ ] Other (please specify below)

### Additional information (optional)

<!--
By default, submitted code will be published on the JASA GitHub repository (http://github.com/JASA-ACS) as well as in the supplementary material. Authors are encouraged to also make their code available in a public repository.
-->

#### Code is also available online at: 

#### Unique identifier / DOI / version information

# Reproducibility workflow

## Scope

The provided workflow reproduces:

- [ ] Any numbers provided in text in the paper
- [ ] All tables and figures in the paper
- [ ] Selected tables and figures in the paper, as explained and justified below:

## Workflow

<!--
The materials provided should provide a straightforward way for reviewers and readers to reproduce analyses with as few steps as possible. 
-->

### Format(s)

<!--
Check all that apply
-->

- [ ] Single master code file 
- [ ] Wrapper (shell) script(s)
- [ ] Self-contained R Markdown file, Jupyter notebook, or other literate programming approach
- [ ] Text file (e.g., a readme-style file) that documents workflow
- [ ] Makefile
- [ ] Other (more detail in *Instructions* below)

### Instructions

<!--
Describe how to use the materials provided to reproduce analyses in the manuscript
-->

### Expected run-time

Approximate time needed to reproduce the analyses on a standard desktop machine:

- [ ] < 1 minute
- [ ] 1-10 minutes
- [ ] 10-60 minutes
- [ ] 1-8 hours
- [ ] > 8 hours
- [ ] Not feasible to run on a desktop machine, as described here:

### Additional information (optional)

<!--
OPTIONAL: Additional documentation provided (e.g., R package vignettes, demos or other examples) that show how to use the provided code/software in other settings.
-->

# Notes (optional)

<!--
OPTIONAL: Any other relevant information not covered on this form
-->